language: java
install: true

services:
  - docker

before_install:
  - docker run -d -p 5000:5000 --restart=always --name registry registry:2
  - ssh-add $GIT_KEY
  - git config user.name "Travis"
  - git config user.email "my007id@gmail.com"
  - git config push.default simple

jdk:
  - openjdk8

script:
  - ./gradlew clean build release -Prelease.useAutomaticVersion=true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

